import FS_WHITE_LOGO from "@/assets/logo bijela.png";
import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Image from "next/image";
import TopNavMenu from "./(navigation)/TopNavMenu";
import "./globals.css";
import Footer from "./(pages)/(shared)/Footer";
import Link from "next/link";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: "Football Stats | %s",
    default: "Football Stats",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={montserrat.className}
        style={{ minHeight: "100vh", display: "flex", flexDirection: "column" }}
      >
        <div className="bg-black/70 h-16 px-6 flex items-center py-10 fixed top-0 w-full z-10">
          <Link href={"/home"}>
            <Image src={FS_WHITE_LOGO} alt="fs_logo" width={50} height={50} />
          </Link>
          <TopNavMenu />
        </div>
        <div style={{ flex: "1 0 auto" }}>{children}</div>
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
